export enum CustomerActionTypes {
    FETCH_CUSTOMER = 'FETCH_CUSTOMER',
    FETCH_CUSTOMER_FULFILLED = 'FETCH_CUSTOMER_FULFILLED',
    FETCH_CUSTOMER_ERROR = 'FETCH_CUSTOMER_ERROR',
    FETCH_CUSTOMER_CANCELLED = 'FETCH_CUSTOMER_CANCELLED'
};
