export enum InternetYearlyUsageActionTypes {
    FETCH_INTERNET_YEARLY_USAGE = 'FETCH_INTERNET_YEARLY_USAGE',
    FETCH_INTERNET_YEARLY_USAGE_FULFILLED = 'FETCH_INTERNET_YEARLY_USAGE_FULFILLED',
    FETCH_INTERNET_YEARLY_USAGE_ERROR = 'FETCH_INTERNET_YEARLY_USAGE_ERROR',
    FETCH_INTERNET_YEARLY_USAGE_CANCELLED = 'FETCH_INTERNET_YEARLY_USAGE_CANCELLED'
};
