export enum InternetUsageActionTypes {
    FETCH_INTERNET_USAGE = 'FETCH_INTERNET_USAGE',
    FETCH_INTERNET_USAGE_FULFILLED = 'FETCH_INTERNET_USAGE_FULFILLED',
    FETCH_INTERNET_USAGE_ERROR = 'FETCH_INTERNET_USAGE_ERROR',
    FETCH_INTERNET_USAGE_CANCELLED = 'FETCH_INTERNET_USAGE_CANCELLED'
};
