export enum InvoicesActionTypes {
    FETCH_INVOICES = 'FETCH_INVOICES',
    FETCH_INVOICES_FULFILLED = 'FETCH_INVOICES_FULFILLED',
    FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR',
    FETCH_INVOICES_CANCELLED = 'FETCH_INVOICES_CANCELLED',
    DOWNLOAD_INVOICE = 'DOWNLOAD_INVOICE',
    DOWNLOAD_INVOICE_FULFILLED = 'DOWNLOAD_INVOICE_FULFILLED',
    DOWNLOAD_INVOICE_ERROR = 'DOWNLOAD_INVOICE_ERROR',
    DOWNLOAD_INVOICE_CANCELLED = 'DOWNLOAD_INVOICE_CANCELLED'
}
