export enum MobileUsageActionTypes {
    FETCH_AVERAGE_MOBILE_USAGE = 'FETCH_AVERAGE_MOBILE_USAGE',
    FETCH_AVERAGE_MOBILE_USAGE_FULFILLED = 'FETCH_AVERAGE_MOBILE_USAGE_FULFILLED',
    FETCH_AVERAGE_MOBILE_USAGE_ERROR = 'FETCH_AVERAGE_MOBILE_USAGE_ERROR',
    FETCH_AVERAGE_MOBILE_USAGE_CANCELLED = 'FETCH_AVERAGE_MOBILE_USAGE_CANCELLED',
    FETCH_MOBILE_CDR = 'FETCH_MOBILE_CDR',
    FETCH_MOBILE_CDR_FULFILLED = 'FETCH_MOBILE_CDR_FULFILLED',
    FETCH_MOBILE_CDR_ERROR = 'FETCH_MOBILE_CDR_ERROR',
    FETCH_MOBILE_CDR_CANCELLED = 'FETCH_MOBILE_CDR_CANCELLED'
};
