export enum MobileSubscriptionsActionTypes {
    FETCH_MOBILE_SUBSCRIPTIONS = 'FETCH_MOBILE_SUBSCRIPTIONS',
    FETCH_MOBILE_SUBSCRIPTIONS_FULFILLED = 'FETCH_MOBILE_SUBSCRIPTIONS_FULFILLED',
    FETCH_MOBILE_SUBSCRIPTIONS_ERROR = 'FETCH_MOBILE_SUBSCRIPTIONS_ERROR',
    FETCH_MOBILE_SUBSCRIPTIONS_CANCELLED = 'FETCH_MOBILE_SUBSCRIPTIONS_CANCELLED',
    SET_SELECTED_MSISDN = 'SET_SELECTED_MSISDN'
};
