export enum PaymentBalanceActionTypes {
    FETCH_PAYMENT_BALANCE = 'FETCH_PAYMENT_BALANCE',
    FETCH_PAYMENT_BALANCE_FULFILLED = 'FETCH_PAYMENT_BALANCE_FULFILLED',
    FETCH_PAYMENT_BALANCE_ERROR = 'FETCH_PAYMENT_BALANCE_ERROR',
    FETCH_PAYMENT_BALANCE_CANCELLED = 'FETCH_PAYMENT_BALANCE_CANCELLED'
};
