export enum PhoneUsageActionTypes {
    SET_SELECTED_PHONE_NUMBER = 'SET_SELECTED_PHONE_NUMBER',
    FETCH_PHONES = 'FETCH_PHONES',
    FETCH_PHONES_FULFILLED = 'FETCH_PHONES_FULFILLED',
    FETCH_PHONES_ERROR = 'FETCH_PHONES_ERROR',
    FETCH_PHONES_CANCELLED = 'FETCH_PHONES_CANCELLED',
    FETCH_PHONE_USAGE = 'FETCH_PHONE_USAGE',
    FETCH_PHONE_USAGE_FULFILLED = 'FETCH_PHONE_USAGE_FULFILLED',
    FETCH_PHONE_USAGE_ERROR = 'FETCH_PHONE_USAGE_ERROR',
    FETCH_PHONE_USAGE_CANCELLED = 'FETCH_PHONE_USAGE_CANCELLED'
};
