export enum TvOptionsActionTypes {
    FETCH_TV_OPTIONS = 'FETCH_TV_OPTIONS',
    FETCH_TV_OPTIONS_FULFILLED = 'FETCH_TV_OPTIONS_FULFILLED',
    FETCH_TV_OPTIONS_ERROR = 'FETCH_TV_OPTIONS_ERROR',
    FETCH_TV_OPTIONS_CANCELLED = 'FETCH_TV_OPTIONS_CANCELLED',
    UPDATE_PARENTAL_CONTROL_AGE = 'UPDATE_PARENTAL_CONTROL_AGE',
    UPDATE_PARENTAL_CONTROL_PIN = 'UPDATE_PARENTAL_CONTROL_PIN',
    UPDATE_VOD_PURCHASE_CODE = 'UPDATE_VOD_PURCHASE_CODE',
    ACTIVATE_TV_OPTIONS = 'ACTIVATE_TV_OPTIONS',
    ACTIVATE_TV_OPTIONS_FULFILLED = 'ACTIVATE_TV_OPTIONS_FULFILLED',
    ACTIVATE_TV_OPTIONS_ERROR = 'ACTIVATE_TV_OPTIONS_ERROR',
    ACTIVATE_TV_OPTIONS_CANCELLED = 'ACTIVATE_TV_OPTIONS_CANCELLED',
}
