export enum VodUsageActionTypes {
    FETCH_VOD_USAGE = 'FETCH_VOD_USAGE',
    FETCH_VOD_USAGE_FULFILLED = 'FETCH_VOD_USAGE_FULFILLED',
    FETCH_VOD_USAGE_ERROR = 'FETCH_VOD_USAGE_ERROR',
    FETCH_VOD_USAGE_CANCELLED = 'FETCH_VOD_USAGE_CANCELLED'
};
