namespace VOO.Mobile.App.Enums {
	export const enum Icon {
		ARROW_LEFT = 'ARROW_LEFT',
		ARROW_RIGHT = 'ARROW_RIGHT',
		DOWNLOAD = 'DOWNLOAD',
		EXCLAMATION_CIRCLED = 'EXCLAMATION_CIRCLED',
		EXCLAMATION = 'EXCLAMATION',
		FACE_SAD = 'FACE_SAD',
		FACE_SMILE = 'FACE_SMILE',
		HAMBURGER = 'HAMBURGER',
		LITTLE_ARROW_DOWN = 'LITTLE_ARROW_DOWN',
		SPEECH_BUBBLE = 'SPEECH_BUBBLE',
		VOO_CIRCLED = 'VOO_CIRCLED',
		WORLD_GLOBE = 'WORLD_GLOBE',
		CHECK_MARK = 'CHECK_MARK',
		EURO = 'EURO',
		FIXE = 'FIXE',
		LIST = 'LIST',
		PHONE = 'PHONE',
		SMARTPHONE = 'SMARTPHONE',
		SMS = 'SMS',
		NET = 'NET',
		DOWNLOAD_INVOICE = 'DOWNLOAD_INVOICE',
		USER = 'USER'
	}
}