import ArrowDownIcon from './ArrowDownIcon';
import ArrowLeftIcon from './ArrowLeftIcon';
import ArrowRightIcon from './ArrowRightIcon';
import ExclamationIcon from './ExclamationIcon';
import CircledExclamationIcon from './CircledExclamationIcon';
import DownloadIcon from './DownloadIcon';
import DownloadInvoiceIcon from './DownloadInvoiceIcon';
import SadFaceIcon from './SadFaceIcon';
import SmileyFaceIcon from './SmileyFaceIcon';
import SpeechBubbleIcon from './SpeechBubbleIcon';
import VooIcon from './VooIcon';
import WorldGlobeIcon from './WorldGlobeIcon';
import CheckMarkIcon from './CheckMarkIcon';
import EuroIcon from './EuroIcon';
import FixeIcon from './FixeIcon';
import ListIcon from './ListIcon';
import HamburgerIcon from './HamburgerIcon';
import PhoneIcon from './PhoneIcon';
import SmartphoneIcon from './SmartphoneIcon';
import SMSIcon from './SMSIcon';
import NetIcon from './NetIcon';
import UserIcon from './UserIcon';

export const ArrowDown = ArrowDownIcon;
export const ArrowLeft = ArrowLeftIcon;
export const ArrowRight = ArrowRightIcon;
export const Exclamation = ExclamationIcon;
export const CircledExclamation = CircledExclamationIcon;
export const Download = DownloadIcon;
export const DownloadInvoice = DownloadInvoiceIcon;
export const SadFace = SadFaceIcon;
export const SmileyFace = SmileyFaceIcon;
export const SpeechBubble = SpeechBubbleIcon;
export const Voo = VooIcon;
export const WorldGlobe = WorldGlobeIcon;
export const CheckMark = CheckMarkIcon;
export const Euro = EuroIcon;
export const Fixe = FixeIcon;
export const List = ListIcon;
export const Hamburger = HamburgerIcon;
export const Phone = PhoneIcon;
export const Smartphone = SmartphoneIcon;
export const Sms = SMSIcon;
export const Net = NetIcon;
export const User = UserIcon;
